# 228-front_right camera config.

fx: 969.83478
fy: 970.26593
cx: 998.49302
cy: 539.27449
k1: -0.307979
k2: 0.065649
p1: -0.001273
p2: -0.003984

# FAST-Calib target parameters. Keep consistent with the current four-hole board.
marker_size: 0.20
delta_width_qr_center: 0.55
delta_height_qr_center: 0.35
delta_width_circles: 0.5
delta_height_circles: 0.4
circle_radius: 0.12
