# Camera parameters for rear left camera of vehicle 228
fx: 1007.71611
fy: 1014.48679
cx: 988.73142
cy: 553.23383
k1: -0.301734
k2: 0.060483
p1: -0.005133
p2: -0.001493

# FAST-Calib target parameters
marker_size: 0.20
delta_width_qr_center: 0.55
delta_height_qr_center: 0.35
delta_width_circles: 0.5
delta_height_circles: 0.4
circle_radius: 0.12
