# 228-front_right camera config.


fx: 1016.2878126862
fy: 1016.3793051983
cx: 957.1085816884
cy: 535.7646428832
k1: 1.9254739483
k2: 0.5438037054
p1: 0.0000553361
p2: 0.0000225784
k3: 0.0132343276
k4: 2.3233229285
k5: 1.1969630386
k6: 0.1050127013
# FAST-Calib target parameters. Keep consistent with the current four-hole board.
# 2000 mm × 1500 mm FAST-Calib calibration target

marker_size: 0.250

# Half of the horizontal/vertical distance between ArUco centers
delta_width_qr_center: 0.725
delta_height_qr_center: 0.500

# Full horizontal/vertical distance between circle centers
delta_width_circles: 0.650
delta_height_circles: 0.650

# Circle diameter: 450 mm
circle_radius: 0.225

# Allow calibration when at least 3 of the 4 markers are detected
min_detected_markers: 3