# 228-front_right camera config.

fx: 1007.40399
fy: 1011.92294
cx: 977.58926
cy: 572.71554
k1: -0.319008
k2: 0.077070
p1: -0.006841
p2: -0.000921
# FAST-Calib target parameters. Keep consistent with the current four-hole board.
marker_size: 0.20
delta_width_qr_center: 0.55
delta_height_qr_center: 0.35
delta_width_circles: 0.5
delta_height_circles: 0.4
circle_radius: 0.12
