# Camera parameters for rear left camera of vehicle 228

fx: 991.26967
fy: 992.31765
cx: 1049.19666
cy: 515.79644
k1: -0.326599
k2: 0.085275
p1: 0.000956
p2: -0.006572
# FAST-Calib target parameters
marker_size: 0.20
delta_width_qr_center: 0.55
delta_height_qr_center: 0.35
delta_width_circles: 0.5
delta_height_circles: 0.4
circle_radius: 0.12
