# 226-front_right camera config.

fx: 1279.88264
fy: 1279.50145
cx: 946.56985
cy: 551.53822
k1: -0.496976
k2: 0.198209
p1: -0.000824
p2: 0.003522


# FAST-Calib target parameters. Keep consistent with the current four-hole board.
marker_size: 0.20
delta_width_qr_center: 0.55
delta_height_qr_center: 0.35
delta_width_circles: 0.5
delta_height_circles: 0.4
circle_radius: 0.12
