vehicle_id: '227'
sensors:
  front:
    enabled: false
    data_dir: /home/glf/dataDisk/calib/0427/227_front
    camera_config: config/vehicles/227/cameras/front.yaml
    roi_profile: config/roi_profiles/hesai/front.yaml
    lidar_topic: auto
  rear:
    enabled: false
    data_dir: /home/glf/dataDisk/calib/0427/227_rear
    camera_config: config/vehicles/227/cameras/rear.yaml
    roi_profile: config/roi_profiles/hesai/rear.yaml
    lidar_topic: auto
  front_left:
    enabled: true
    data_dir: /home/glf/dataDisk/calib/0427/227_left_front
    camera_config: config/vehicles/227/cameras/front_left.yaml
    roi_profile: config/roi_profiles/hesai/front_left.yaml
    lidar_topic: auto
    fast_calib:
      multi_mode: permutation_search
  rear_right:
    enabled: false
    data_dir: /home/glf/dataDisk/calib/0427/227_right_rear
    camera_config: config/vehicles/227/cameras/rear_right.yaml
    roi_profile: config/roi_profiles/hesai/rear_right.yaml
    lidar_topic: auto
