# Camera intrinsics  
  # mid360
  # fx: 843.501050605967
  # fy: 845.199690011973
  # cx: 321.017429415352
  # cy: 239.294896816737
  # k1: -0.465219389887045
  # k2: 0.237050091701749
  # p1: 0.00521922785740506
  # p2: 0.000418186016514835

  # avia
  # fx: 1215.31801774424
  # fy: 1214.72961288138
  # cx: 1047.86571859677
  # cy: 745.068353101898
  # k1: -0.33574781188503
  # k2: 0.10996870793601
  # p1: 0.000157303079833973
  # p2: 0.000544930726278493

  # ouster
  # fx: 1466.16500795563
  # fy: 1465.32657394431
  # cx: 1214.39964380518
  # cy: 1010.97681425650
  # k1: -0.0458344972140773
  # k2: 0.0896961240772692
  # p1: -0.000731746350601389
  # p2: -0.000201478932371979

  # multi-scene
 # Camera intrinsics
  fx: 1030.06731324
  fy: 1030.51267838
  cx: 965.00523357
  cy: 527.49974735
  k1: -0.3319521991
  k2: 0.0867648655
  p1: 0.0008438102
  p2: -0.0006867438

# Calibration target parameters
  marker_size: 0.20 # ArUco marker size (our test data uses 0.16m; adjust to match your marker size)
  delta_width_qr_center: 0.55 # Half the distance between the centers of two markers in the horizontal direction 
  delta_height_qr_center: 0.35 # Half the distance between the centers of two markers in the vertical direction
  delta_width_circles: 0.5 # Distance between the centers of two circles in the horizontal direction
  delta_height_circles: 0.4 # Distance between the centers of two circles in the vertical direction
  circle_radius: 0.12 # Radius of the circle 

# Distance filter
  # x_min: 3.0 # avia and mid360: 2.0 ouster: 1.5
  # x_max: 5.0
  # y_min: -0.5
  # y_max: 3.0
  # z_min: 0.0 # avia and mid360: -0.5 ouster: -0.8
  # z_max: 2.0

# multi_scene_11
  # x_min: 2.0
  # x_max: 5.0
  # y_min: -1.0
  # y_max: 1.0
  # z_min: 0.0
  # z_max: 2.0
# multi_scene_22
  # x_min: 2.0
  # x_max: 5.0
  # y_min: -4.0
  # y_max: 1.0
  # z_min: 0.0
  # z_max: 2.0
# multi_scene_33
  # # 1 组  ok 
  # x_min: -0.55
  # x_max: 1.45
  # y_min: 0.30
  # y_max: 2.50
  # z_min: 2.65
  # z_max: 3.40
  # # 2组 ok
  # x_min: -0.45
  # x_max: 1.40
  # y_min: 0.35
  # y_max: 2.45
  # z_min: 2.70
  # z_max: 3.50
  #   # 3 组 ok
  # x_min: -0.45
  # x_max: 1.21
  # y_min: 0.35
  # y_max: 2.09
  # z_min: 1.85
  # z_max: 3.27
  # 4 组   not good, 这组场景的板子姿态更斜，导致孔边界点太差。
  # x_min: -0.45
  # x_max: 1.21
  # y_min: 0.35
  # y_max: 2.09
  # z_min: 1.85
  # z_max: 3.27
  # 5 组
  # x_min: -0.86
  # x_max: 0.92
  # y_min: -0.20
  # y_max: 1.85
  # z_min: 1.18
  # z_max: 2.12
  # 6 组
  # x_min: -1.94
  # x_max: -0.15
  # y_min: -1.90
  # y_max: -0.14
  # z_min: 1.42
  # z_max: 2.61
  # 7 组  一般般
  # x_min: -1.66
  # x_max: 0.19
  # y_min: -1.60
  # y_max: 0.44
  # z_min: 2.24
  # z_max: 2.80
  # 8 组   ok
  # x_min: -1.77
  # x_max: 0.10
  # y_min: -1.50
  # y_max: 0.34
  # z_min: 1.21
  # z_max: 2.70
  # 9 组    super good
  x_min: -1.31
  x_max: 0.64
  y_min: -0.82
  y_max: 1.28
  z_min: 1.56
  z_max: 2.27
# Input
  pointcloud_source: "bag" # "bag" or "pcd"
  lidar_topic: "/velodyne_front" # /ouster/points /livox/lidar
  bag_path: "$(find fast_calib)/calib_data/0421/front/9.bag"
  pcd_path: "$(find fast_calib)/calib_data/0421/front/9.pcd"
  image_path: "$(find fast_calib)/calib_data/0421/front/9.jpg"

# Output
  output_path: "$(find fast_calib)/output/0421/front/9"
