
pair_name: "left_pair_rear_to_front"

data_dir: "/home/glf/dataDisk/calib/left_pair"
output_dir: "/home/glf/dataDisk/calib/output/two_camera/left_pair_rear_to_front"

cam0:
  name: "rear_left"
  fx: 1020.321275
  fy: 1026.490039
  cx: 958.172619
  cy: 522.228574
  k1: -0.289258
  k2: 0.056707
  p1: 0.001357
  p2: -0.000796

cam1:
  name: "front_left"
  fx: 1012.229557
  fy: 1013.831352
  cx: 925.288190
  cy: 514.768269
  k1: -0.303981
  k2: 0.067020
  p1: 0.000418
  p2: 0.000216

target:
  dictionary: "DICT_6X6_250"
  marker_size_m: 0.20
  delta_width_qr_center_m: 0.55
  delta_height_qr_center_m: 0.35
  delta_width_circles_m: 0.50
  delta_height_circles_m: 0.40

runtime:
  min_detected_markers: 3
  refine_markers: 0
  reproj_rmse_thresh_px: 6.0
  outlier_rot_thresh_deg: 1.0
  outlier_trans_thresh_m: 0.10
  min_valid_pairs: 2
  save_debug: 1