#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Export a six-camera summary as individual ROS TF YAML files.

The input is generated by ``summarize_vehicle_extrinsics.py``.  Each output
stores T_lidar_camera (LiDAR parent, camera child), matching the layout used by
``/home/guoli/data/227``.
"""

import argparse
import math
from pathlib import Path
from typing import Any, Dict, Iterable, List

import yaml


CAMERA_SPECS = [
    ("front", "camera_front"),
    ("front_left", "front_left_camera_frame"),
    ("front_right", "front_right_camera_frame"),
    ("rear", "rear_camera_frame"),
    ("rear_left", "rear_left_camera_frame"),
    ("rear_right", "rear_right_camera_frame"),
]


def load_yaml(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as stream:
        value = yaml.safe_load(stream)
    if not isinstance(value, dict):
        raise ValueError("{} must contain a YAML mapping".format(path))
    return value


def as_matrix4(value: Any, name: str) -> List[List[float]]:
    if not isinstance(value, list) or len(value) != 4:
        raise ValueError("{} must be a 4x4 matrix".format(name))
    matrix = []
    for row in value:
        if not isinstance(row, list) or len(row) != 4:
            raise ValueError("{} must be a 4x4 matrix".format(name))
        matrix.append([float(item) for item in row])
    return matrix


def invert_rigid_transform(matrix: List[List[float]]) -> List[List[float]]:
    rotation = [row[:3] for row in matrix[:3]]
    translation = [matrix[row][3] for row in range(3)]
    inverse = [[0.0] * 4 for _ in range(4)]
    for row in range(3):
        for column in range(3):
            inverse[row][column] = rotation[column][row]
        inverse[row][3] = -sum(rotation[column][row] * translation[column] for column in range(3))
    inverse[3][3] = 1.0
    return inverse


def inverse_quaternion_xyzw(value: Iterable[Any], name: str) -> List[float]:
    quaternion = [float(item) for item in value]
    if len(quaternion) != 4:
        raise ValueError("{} must contain x, y, z, w".format(name))
    norm = math.sqrt(sum(item * item for item in quaternion))
    if not math.isfinite(norm) or abs(norm - 1.0) > 1e-5:
        raise ValueError("{} is not a unit quaternion (norm={})".format(name, norm))
    x, y, z, w = quaternion
    return [-x, -y, -z, w]


def number(value: float) -> str:
    text = "{:.10f}".format(float(value)).rstrip("0").rstrip(".")
    return "0" if text in {"-0", ""} else text


def render(camera: str, lidar_frame: str, camera_frame: str,
           translation: Iterable[float], quaternion: Iterable[float]) -> str:
    tx, ty, tz = translation
    qx, qy, qz, qw = quaternion
    return (
        "/camera_extrinsic_{camera}:\n"
        "  header:\n"
        "    frame_id: \"{lidar_frame}\"\n"
        "  child_frame_id: \"{camera_frame}\"\n"
        "  transform:\n"
        "    translation:\n"
        "      x: {tx}\n"
        "      y: {ty}\n"
        "      z: {tz}\n"
        "    rotation:\n"
        "      x: {qx}\n"
        "      y: {qy}\n"
        "      z: {qz}\n"
        "      w: {qw}\n"
    ).format(
        camera=camera,
        lidar_frame=lidar_frame,
        camera_frame=camera_frame,
        tx=number(tx),
        ty=number(ty),
        tz=number(tz),
        qx=number(qx),
        qy=number(qy),
        qz=number(qz),
        qw=number(qw),
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export six individual LiDAR-parent camera-child ROS TF YAML files."
    )
    parser.add_argument("summary", type=Path, help="All-camera extrinsics YAML")
    parser.add_argument("output_dir", type=Path, help="Destination directory")
    args = parser.parse_args()

    source = load_yaml(args.summary.expanduser().resolve())
    extrinsics = source.get("extrinsics")
    if not isinstance(extrinsics, dict):
        raise ValueError("{} has no extrinsics mapping".format(args.summary))

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    written = []
    for camera, camera_frame in CAMERA_SPECS:
        entry = extrinsics.get(camera)
        if not isinstance(entry, dict):
            raise ValueError("Missing extrinsics.{}".format(camera))

        lidar_frame = str(entry.get("lidar_topic") or "").strip()
        if not lidar_frame:
            raise ValueError("Missing extrinsics.{}.lidar_topic".format(camera))

        if entry.get("T_lidar_cam") is not None:
            transform = as_matrix4(entry["T_lidar_cam"], "{}.T_lidar_cam".format(camera))
        else:
            camera_from_lidar = as_matrix4(
                entry.get("T_cam_lidar"), "{}.T_cam_lidar".format(camera)
            )
            transform = invert_rigid_transform(camera_from_lidar)

        quaternion = inverse_quaternion_xyzw(
            entry.get("quaternion_xyzw_cam_lidar"),
            "{}.quaternion_xyzw_cam_lidar".format(camera),
        )
        translation = [transform[row][3] for row in range(3)]
        output_path = output_dir / "camera-extrinsic-{}.yaml".format(camera.replace("_", "-"))
        output_path.write_text(
            render(camera, lidar_frame, camera_frame, translation, quaternion),
            encoding="utf-8",
        )
        written.append(output_path)

    print("Exported {} camera extrinsics to {}".format(len(written), output_dir))
    for path in written:
        print(path)


if __name__ == "__main__":
    main()
