# 223-front_right camera config.

fx: 1026.40556
fy: 1031.70964
cx: 992.85456
cy: 553.37725
k1: -0.312819
k2: 0.073599
p1: -0.001852
p2: -0.001978


# FAST-Calib target parameters. Keep consistent with the current four-hole board.
marker_size: 0.20
delta_width_qr_center: 0.55
delta_height_qr_center: 0.35
delta_width_circles: 0.5
delta_height_circles: 0.4
circle_radius: 0.12
